apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deploy-green
  namespace: guestbook-ns
spec:
  selector:
    matchLabels:
      app: guestbook-deploy-green
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook-deploy-green
    spec:
      containers:
      - name: guestbookgreen
        image: tenzai/guestbookgreen
        ports:
          - containerPort: 3000
            name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc-green
  namespace: guestbook-ns
spec:
  selector:
    app: guestbook-deploy-green
  type: NodePort 
  ports:
    - name: guestbook-green
      port: 8080
      targetPort: 3000