apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-g
  namespace: guestbook-ns
  labels:
    app: guestbook-g
spec:
  selector:
    matchLabels:
      app: guestbook-g
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook-g
    spec:
      containers:
      - name: guestbook
        image: tenzai/guestbookg
        ports:
          - containerPort: 3000
            name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-g
  namespace: guestbook-ns
  labels:
    app: guestbook-g
spec:
  selector:
    app: guestbook-g
  type: LoadBalancer 
  ports:
    - name: guestbook
      port: 80
      targetPort: 3000