apiVersion: v1
kind: Service
metadata:
  name: redis-slave-blue
  namespace: guestbook-ns
  labels:
    app: redis-blue
    role: slave-blue
spec:
  selector:
    app: redis-blue
    role: slave-blue
  ports:
    - name: redis-slave-blue
      port: 6379
      targetPort: redis-server