apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: guestbook-ns
  labels:
    app: redis-blue
    role: master-blue
spec:
  selector:
    matchLabels:
      app: redis-blue
      role: master-blue
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-blue
        role: master-blue
    spec:
      containers:
      - name: redis-master-blue
        image: k8s.gcr.io/redis:e2e
        ports:
          - containerPort: 6379
            name: redis-server