apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: guestbook-ns
  labels:
    app: redis-blue
    role: master-blue
spec:
  selector:
    app: redis-blue
    role: master-blue
  ports:
    - name: redis-master-blue
      port: 6379
      targetPort: redis-server