apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-green
  namespace: guestbook-ns
  labels:
    app: redis-green
    role: slave-green
spec:
  selector:
    matchLabels:
      app: redis-green
      role: slave-green
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-green
        role: slave-green
    spec:
      containers:
      - name: redis-slave-green
        image: k8s.gcr.io/redis-slave:v2
        ports:
          - containerPort: 6379
            name: redis-server