apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-masterg
  namespace: guestbook-ns
  labels:
    app: redisg
    role: masterg
spec:
  selector:
    matchLabels:
      app: redisg
      role: masterg
  replicas: 1
  template:
    metadata:
      labels:
        app: redisg
        role: masterg
    spec:
      containers:
      - name: redis-master
        image: k8s.gcr.io/redis:e2e
        ports:
          - containerPort: 6379
            name: redis-server
---
apiVersion: v1
kind: Service
metadata:
  name: redis-masterg
  namespace: guestbook-ns
  labels:
    app: redisg
    role: masterg
spec:
  selector:
    app: redisg
    role: masterg
  ports:
    - name: redis-master
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slaveg
  namespace: guestbook-ns
  labels:
    app: redisg
    role: slaveg
spec:
  selector:
    matchLabels:
      app: redisg
      role: slaveg
  replicas: 1
  template:
    metadata:
      labels:
        app: redisg
        role: slaveg
    spec:
      containers:
      - name: redis-slave
        image: k8s.gcr.io/redis-slave:v2
        ports:
          - containerPort: 6379
            name: redis-server
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slaveg
  namespace: guestbook-ns
  labels:
    app: redisg
    role: slaveg
spec:
  selector:
    app: redisg
    role: slaveg
  ports:
    - name: redis-slave
      port: 6379
      targetPort: 6379