apiVersion: v1
kind: Service
metadata:
  name: redis-slave-green
  namespace: guestbook-ns
  labels:
    app: redis-green
    role: slave-green
spec:
  selector:
    app: redis-green
    role: slave-green
  ports:
    - name: redis-slave-green
      port: 6379
      targetPort: redis-server